Hwv.Trace = DS.Model.extend({
    instance: DS.belongsTo('instance'),
    previous_trace: DS.belongsTo('trace'),
    car: DS.belongsTo('car'),
    step: DS.belongsTo('step'),
    organization: DS.belongsTo('organization'),
    user: DS.belongsTo('user'),
    workshop: DS.belongsTo('workshop'),
    console: DS.belongsTo('console'),
    // next_step: DS.belongsTo('step'),
    // next_organization: DS.belongsTo('organization'),
    // next_workshop: DS.belongsTo('workshop'),
    // next_console: DS.belongsTo('console'),
    start_date: DS.attr('string'),
    end_date: DS.attr('string'),
    is_finished: DS.attr('boolean', {defaultValue: false}),
    yellow_due: DS.attr('string'),
    red_due: DS.attr('string'),
    color: DS.attr('string'),
    info: DS.attr('string'),
    handler: DS.belongsTo('user'),
    creater: DS.belongsTo('user'),
    created_date: DS.attr('string'),
    modifier: DS.belongsTo('user'),
    modified_date: DS.attr('string'),
    /**
     * [realTimeoutColor 全局定时器定时更新该属性值，只更新is_finished为false的trace]
     * @return {[sttring]} [颜色gray/green/yellow/red]
     */
    realTimeoutColor:function(){
        if(this.get("is_finished")){
            return this.get("color");
        }
        else{
            var now = new Date();
            if(now > new Date(this.get("red_due"))){
                return "red";
            }
            else if(now > new Date(this.get("yellow_due"))){
                return "yellow";
            }
            else{
                return this.get("color");
            }
        }
    }.property("is_finished","color"),
    approves:function(){
        return this.store.all("approve").filterBy("trace.id",this.get("id"));
    }.property("modified_date")
});

Hwv.Trace.FIXTURES = [
    {
        id:1,
        instance: 1,
        previous_trace:null,
        car: 1,
        step: 1,
        organization: 1,
        user: 1,
        workshop: null,
        console: null,
        // next_step: null,
        // next_organization: null,
        // next_workshop: null,
        // next_console: null,
        start_date: '2014-01-02 12:02:00',
        end_date: null,
        is_finished: false,
        yellow_due: null,
        red_due: null,
        color: 'green',
        info: '',
        handler: 1,
        creater: 1,
        created_date: '2014-02-03 12:03:00',
        modifier: 1,
        modified_date: '2014-02-03 12:03:00'
    },
    {
        id:2,
        instance: 2,
        previous_trace:null,
        car: 2,
        step: 1,
        organization: 1,
        user: 1,
        workshop: null,
        console: null,
        // next_step: null,
        // next_organization: 9,
        // next_workshop: 2,
        // next_console: null,
        start_date: '2014-02-03 12:03:00',
        end_date: '2014-02-03 12:23:00',
        is_finished: true,
        yellow_due: '2014-02-03 12:30:00',
        red_due: '2014-02-03 12:50:00',
        color: 'green',
        info: '准备好了，可以装车了',
        handler: 1,
        creater: 1,
        created_date: '2014-02-03 12:03:00',
        modifier: 1,
        modified_date: '2014-02-03 12:23:00'
    },
    {
        id:22,
        instance: 2,
        previous_trace:2,
        car: 2,
        step: 5,
        organization: 8,
        user: null,
        workshop: 2,
        console: null,
        // next_step: null,
        // next_organization: null,
        // next_workshop: null,
        // next_console: null,
        start_date: '2014-02-03 12:23:00',
        end_date: '2014-02-03 14:43:00',
        is_finished: true,
        yellow_due: '2014-02-03 13:03:00',
        red_due: '2014-02-03 14:03:00',
        color: 'green',
        info: '车安装完成，请工程师检查下',
        handler: 8,
        creater: 1,
        created_date: '2014-02-03 12:23:00',
        modifier: 1,
        modified_date: '2014-02-03 14:43:00'
    },
    {
        id:222,
        instance: 2,
        previous_trace:22,
        car: 2,
        step: 4,
        organization: 3,
        user: null,
        workshop: 2,
        console: null,
        // next_step: null,
        // next_organization: null,
        // next_workshop: null,
        // next_console: null,
        start_date: '2014-02-03 14:43:00',
        end_date: '2014-02-03 15:03:00',
        is_finished: true,
        yellow_due: '2014-02-03 15:00:00',
        red_due: '2014-02-03 15:33:00',
        color: 'yellow',
        info: '',
        handler: 10,
        creater: 1,
        created_date: '2014-02-03 14:43:00',
        modifier: 1,
        modified_date: '2014-02-03 15:03:00'
    },
    {
        id:2222,
        instance: 2,
        previous_trace:22,
        car: 2,
        step: 7,
        organization: 4,
        user: 7,
        workshop: 2,
        console: null,
        // next_step: null,
        // next_organization: null,
        // next_workshop: null,
        // next_console: null,
        start_date: '2014-02-03 15:03:00',
        end_date: null,
        is_finished: false,
        yellow_due: '2014-02-03 16:13:00',
        red_due: '2014-02-03 16:33:00',
        color: 'green',
        info: '',
        handler: 7,
        creater: 1,
        created_date: '2014-02-03 15:03:00',
        modifier: 1,
        modified_date: '2014-02-03 15:03:00'
    },
    {
        id:3,
        instance: 3,
        previous_trace:null,
        car: 3,
        step: 1,
        organization: 1,
        user: 1,
        workshop: null,
        console: null,
        // next_step: null,
        // next_organization: 9,
        // next_workshop: 2,
        // next_console: null,
        start_date: '2014-02-03 12:03:00',
        end_date: '2014-02-03 14:03:00',
        is_finished: true,
        yellow_due: '2014-02-03 14:03:00',
        red_due: '2014-02-03 15:03:00',
        color: 'green',
        info: '准备好了，可以装车了',
        handler: 1,
        creater: 1,
        created_date: '2014-02-03 12:03:00',
        modifier: 1,
        modified_date: '2014-02-03 14:03:00'
    },
    {
        id:33,
        instance: 3,
        previous_trace:3,
        car: 3,
        step: 8,
        organization: 4,
        user: null,
        workshop: null,
        console: 1,
        // next_step: null,
        // next_organization: null,
        // next_workshop: null,
        // next_console: null,
        start_date: '2014-02-03 14:03:00',
        end_date: null,
        is_finished: false,
        yellow_due: null,
        red_due: null,
        color: 'green',
        info: '',
        handler: null,
        creater: 1,
        created_date: '2014-02-03 14:03:00',
        modifier: 1,
        modified_date: '2014-02-03 14:03:00'
    },
    {
        id:4,
        instance: 4,
        previous_trace:null,
        car: 4,
        step: 1,
        organization: 1,
        user: null,
        workshop: null,
        console: null,
        // next_step: null,
        // next_organization: null,
        // next_workshop: null,
        // next_console: null,
        start_date: '2014-05-02 08:03:00',
        end_date: '2014-05-02 09:03:00',
        is_finished: true,
        yellow_due: null,
        red_due: null,
        color: 'green',
        info: '',
        handler: 1,
        creater: 1,
        created_date: '2014-05-02 09:03:00',
        modifier: 1,
        modified_date: '2014-05-02 09:03:00'
    },
    {
        id:44,
        instance: 4,
        previous_trace:4,
        car: 4,
        step: 11,
        organization: 2,
        user: null,
        workshop: null,
        console: null,
        // next_step: null,
        // next_organization: null,
        // next_workshop: null,
        // next_console: null,
        start_date: '2014-05-02 09:03:00',
        end_date: null,
        is_finished: false,
        yellow_due: null,
        red_due: null,
        color: 'green',
        info: '',
        handler: null,
        creater: 1,
        created_date: '2014-05-02 09:03:00',
        modifier: 1,
        modified_date: '2014-05-02 09:03:00'
    }
];
